// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Example.Mobile.EntityFrameworkCore.DbContexts;

namespace Example.Mobile.EntityFrameworkCore.Migrations.ExampleMobile
{
    [DbContext(typeof(ExampleMobileDbContext))]
    [Migration("20200226082605_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Example.Mobile.EntityFrameworkCore.Entities.Command", b =>
                {
                    b.Property<long>("SequenceNo")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CorrelationId");

                    b.Property<string>("Data");

                    b.Property<Guid>("Id");

                    b.Property<string>("Name");

                    b.Property<string>("Subject");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.Property<string>("Type");

                    b.Property<string>("UserId");

                    b.HasKey("SequenceNo");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Name");

                    b.HasIndex("Subject");

                    b.ToTable("Command","log");
                });

            modelBuilder.Entity("Example.Mobile.EntityFrameworkCore.Entities.Event", b =>
                {
                    b.Property<long>("SequenceNo")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CausationId");

                    b.Property<Guid?>("CorrelationId");

                    b.Property<string>("Data");

                    b.Property<Guid>("Id");

                    b.Property<string>("Name");

                    b.Property<string>("Subject");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.Property<string>("Type");

                    b.Property<string>("UserId");

                    b.HasKey("SequenceNo");

                    b.HasIndex("CausationId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Name");

                    b.HasIndex("Subject");

                    b.ToTable("Event","log");
                });

            modelBuilder.Entity("Example.Mobile.EntityFrameworkCore.Entities.Query", b =>
                {
                    b.Property<long>("SequenceNo")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CorrelationId");

                    b.Property<string>("Data");

                    b.Property<Guid>("Id");

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.Property<string>("Type");

                    b.Property<string>("UserId");

                    b.HasKey("SequenceNo");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Name");

                    b.ToTable("Query","log");
                });
#pragma warning restore 612, 618
        }
    }
}
